/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redjalica2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Timer;

/**
 *
 * @author Laki
 */
public class skocko extends javax.swing.JFrame {

    /**
     * Creates new form skocko
     */
     private Timer timer ;
    public skocko() {
        initComponents();
            timer = new Timer(1000, new ActionListener() { // 5000 is five Second
            @Override
            public void actionPerformed(ActionEvent e) {
              //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           
            countme();
            }
        });
      
       timer.start();
    }
    int i = 60;
    
   public void countme(){
   
   i-- ;
   
   jLabel2.setText(String.valueOf(i));
   
       this.setSize(1100, 750);
    this.setResizable(false);
   
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel50 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textField3 = new java.awt.TextField();
        textField1 = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel50.setBackground(new java.awt.Color(198, 220, 186));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(215, 228, 192));
        jLabel2.setText("0");
        jPanel50.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        jButton12.setBackground(new java.awt.Color(215, 228, 192));
        jButton12.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(127, 127, 127));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/back-removebg-preview.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, 60, 60));

        jButton4.setBackground(new java.awt.Color(215, 228, 192));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(127, 127, 127));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/close-removebg-preview.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 60, 60));

        jButton2.setBackground(new java.awt.Color(215, 228, 192));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja2-removebg-preview.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 50, 50));

        jButton3.setBackground(new java.awt.Color(215, 228, 192));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja1-Photoroom.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 50, 50));

        jButton5.setBackground(new java.awt.Color(215, 228, 192));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/BOJA4-removebg-preview.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 50, 50));

        jButton6.setBackground(new java.awt.Color(215, 228, 192));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/bojA3-removebg-preview.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 50, 50));

        jButton7.setBackground(new java.awt.Color(215, 228, 192));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja6-removebg-preview.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 50, 50));

        jButton8.setBackground(new java.awt.Color(215, 228, 192));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja5-removebg-preview.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 50, 50));

        jButton9.setBackground(new java.awt.Color(215, 228, 192));
        jButton9.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(127, 127, 127));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/zvučnik-removebg-preview.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 60, 60));

        jButton31.setBackground(new java.awt.Color(187, 195, 164));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja6-removebg-preview.png"))); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 50, 50));

        jButton34.setBackground(new java.awt.Color(187, 195, 164));
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja6-removebg-preview.png"))); // NOI18N
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 50, 50));

        jButton35.setBackground(new java.awt.Color(187, 195, 164));
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja6-removebg-preview.png"))); // NOI18N
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 50, 50));

        jButton36.setBackground(new java.awt.Color(187, 195, 164));
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja6-removebg-preview.png"))); // NOI18N
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 50, 50));

        jButton30.setBackground(new java.awt.Color(187, 195, 164));
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/BOJA4-removebg-preview.png"))); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 50, 50));

        jButton32.setBackground(new java.awt.Color(187, 195, 164));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/BOJA4-removebg-preview.png"))); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 50, 50));

        jButton33.setBackground(new java.awt.Color(187, 195, 164));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/BOJA4-removebg-preview.png"))); // NOI18N
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 50, 50));

        jButton37.setBackground(new java.awt.Color(187, 195, 164));
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/BOJA4-removebg-preview.png"))); // NOI18N
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 50, 50));

        jButton38.setBackground(new java.awt.Color(187, 195, 164));
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/bojA3-removebg-preview.png"))); // NOI18N
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 50, 50));

        jButton39.setBackground(new java.awt.Color(187, 195, 164));
        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/bojA3-removebg-preview.png"))); // NOI18N
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 50, 50));

        jButton40.setBackground(new java.awt.Color(187, 195, 164));
        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/bojA3-removebg-preview.png"))); // NOI18N
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 50, 50));

        jButton41.setBackground(new java.awt.Color(187, 195, 164));
        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/bojA3-removebg-preview.png"))); // NOI18N
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 50, 50));

        jButton10.setBackground(new java.awt.Color(187, 195, 164));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja2-removebg-preview.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 50, 50));

        jButton11.setBackground(new java.awt.Color(187, 195, 164));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja2-removebg-preview.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 50, 50));

        jButton13.setBackground(new java.awt.Color(187, 195, 164));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja2-removebg-preview.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 50, 50));

        jButton14.setBackground(new java.awt.Color(187, 195, 164));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja2-removebg-preview.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 50, 50));

        jButton15.setBackground(new java.awt.Color(187, 195, 164));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja1-Photoroom.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 50, 50));

        jButton16.setBackground(new java.awt.Color(187, 195, 164));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja1-Photoroom.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 50, 50));

        jButton17.setBackground(new java.awt.Color(187, 195, 164));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja1-Photoroom.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 50, 50));

        jButton18.setBackground(new java.awt.Color(187, 195, 164));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja1-Photoroom.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 50, 50));

        jButton19.setBackground(new java.awt.Color(187, 195, 164));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja5-removebg-preview.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 50, 50));

        jButton20.setBackground(new java.awt.Color(187, 195, 164));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja5-removebg-preview.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 50, 50));

        jButton21.setBackground(new java.awt.Color(187, 195, 164));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja5-removebg-preview.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 50, 50));

        jButton22.setBackground(new java.awt.Color(187, 195, 164));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/boja5-removebg-preview.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 50, 50));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(215, 228, 192));
        jLabel1.setText("ČOVEK");
        jPanel50.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(215, 228, 192));
        jLabel5.setText("KOMPJUTER");
        jPanel50.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        textField3.setBackground(new java.awt.Color(187, 195, 164));
        textField3.setEditable(false);
        textField3.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jPanel50.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 80, 40));

        textField1.setBackground(new java.awt.Color(187, 195, 164));
        textField1.setEditable(false);
        textField1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jPanel50.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 80, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, 30));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, 30));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/tacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 30, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 30, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 30, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 30, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/nijenamestu-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 30, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 30, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/netacno-removebg-preview.png"))); // NOI18N
        jPanel50.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 30, 30));

        jLabel3.setBackground(new java.awt.Color(198, 220, 186));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(215, 228, 192));
        jLabel3.setText("MIŠ");
        jPanel50.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 180, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 80)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        jLabel4.setText("MIŠ");
        jPanel50.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 190, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/vecavecaplocica643.png"))); // NOI18N
        jPanel50.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1200, 630));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/redjalica/slike/pozadina1234.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel50.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1100, 770));

        getContentPane().add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
   playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

        meni m1 = new meni();
        m1.show();
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

        KOZNAZNA k1 = new KOZNAZNA();
    k1.show();
    dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
       playSound("C:\\Users\\Laki\\Documents\\NetBeansProjects\\Redjalica2\\src\\com\\mycompany\\redjalica\\slike\\klikati.wav");

    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(skocko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(skocko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(skocko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(skocko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new skocko().setVisible(true);
            }
        });
    }
        private void playSound(String soundFile) {
    try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundFile).getAbsoluteFile());
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        e.printStackTrace();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel50;
    private java.awt.TextField textField1;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
